### ISSUE TITLE
Fix warnings emitted in compilation and runtime

### ISSUE THREAD

**Issue by vincentvanbush** [curiosum-dev/permit#38]
Compile-time warning in tests, straightforward to fix:
```elixir
warning: :logger :level has been set to :warn in config files, please use :warning instead
```

The second one has been more difficult to fix, occuring when defining permissions using the binding syntax. For instance, this definition:
```elixir
permit()
|> permission_to(:read, TestObject, [s],
  field_1: s.id,
  field_2: {:<, s.overseer_id}
)
```
leads to the AST of the `s.id` expression being processed with the omission of the `no_parens: true` metadata keyword, which produces this obscure warning:
```elixir
warning: using module.function() notation (with parentheses) to fetch map field :id is deprecated, you must remove the parentheses: map.field
  (elixir 1.17.2) src/elixir.erl:386: :elixir.eval_external_handler/3
  (permit 0.2.0) lib/permit/permissions/operators/eq.ex:8: anonymous fn/5 in Permit.Operators.Eq.semantics/2
  (elixir 1.17.2) lib/enum.ex:4226: Enum.predicate_list/3
  test/permit/authorization_test.exs:206: Permit.AuthorizationTest."test permission granting to subject with role should grant permissions to binder subject"/1
  (ex_unit 1.17.2) lib/ex_unit/runner.ex:485: ExUnit.Runner.exec_test/2
  (stdlib 4.3.1.4) timer.erl:235: :timer.tc/1
  (ex_unit 1.17.2) lib/ex_unit/runner.ex:407: anonymous fn/6 in ExUnit.Runner.spawn_test_monitor/4
```

It is likely to be resolved by preserving the meta key in the return value of https://github.com/curiosum-dev/permit/blob/master/lib/permit/permissions/condition_parser.ex#L141.

**Comment by vincentvanbush** [comment]
Closing via #39 and 86a5299.
